name: 'Playwright Summary'
description: 'Processes Playwright test results and formats a summary for GitHub job summaries'
inputs:
  test-results:
    description: 'Path to the test results file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Read test results'
      id: read-results
      run: |
        cat ${{ inputs.test-results }} > results.txt
    - name: 'Format summary'
      id: format-summary
      run: |
        echo "## Playwright Test Summary" > summary.md
        echo "" >> summary.md
        cat results.txt >> summary.md
    - name: 'Upload summary'
      uses: actions/upload-artifact@v2
      with:
        name: playwright-summary
        path: summary.md